export const imoveis = {
  venda: [
    {
      id: '1',
      titulo: 'Linda Casa no Rio Tavares com vista para o Mar',
      imagem:
        'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      detalhe: 'Imóvel Residencial',
      tipo: 'Apartamento',
      local: 'Campeche',
      valor: '400.000,00',
      dormitorios: 1,
      suites: 1,
      banheiros: 2,
      salas: 1,
      garagem: 4,
      garagem_coberta: 2,
      area_total: 180,
      areaUtil: 180,
      estrutura: ['Ar condicionado', 'Churrasqueira', 'Despensa', 'Escritório'],
      mapa: 'https://goo.gl/maps/BkjiniR8JcaRHeiw5',
    },
    {
      id: '2',
      titulo: 'Casa com 3 dormitorios no Campeche com ótima vista',
      imagem:
        'https://images.pexels.com/photos/2468773/pexels-photo-2468773.jpeg?cs=srgb&dl=pexels-krisp-cut-2468773.jpg&fm=jpg',
      detalhe: 'Imóvel Residencial',
      tipo: 'Apartamento',
      local: 'Coqueiros',
      valor: '350.000,00',
      dormitorios: 1,
      suites: 1,
      banheiros: 2,
      salas: 1,
      garagem: 4,
      garagem_coberta: 2,
      area_total: 180,
      area_util: 180,
      estrutura: ['Ar condicionado', 'Churrasqueira', 'Despensa', 'Escritório'],
      mapa: 'https://goo.gl/maps/BkjiniR8JcaRHeiw5',
    },
    {
      id: '3',
      titulo: 'Apartamento no prédio XPTO com vista para a Lagoa',
      imagem:
        'https://images.pexels.com/photos/1296203/pexels-photo-1296203.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      detalhe: 'Comercial/Industrial',
      tipo: 'Sala Comercial',
      local: 'Itacorubi',
      valor: '600.000,00',
      dormitorios: 1,
      suites: 1,
      banheiros: 2,
      salas: 1,
      garagem: 4,
      garagem_coberta: 2,
      area_total: 180,
      area_util: 180,
      estrutura: ['Ar condicionado', 'Churrasqueira', 'Despensa', 'Escritório'],
      mapa: 'https://goo.gl/maps/BkjiniR8JcaRHeiw5',
    },
  ],
  aluguel: [
    {
      id: '4',
      titulo: 'Linda Casa no Rio Tavares com vista para o Mar',
      imagem:
        'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      detalhe: 'Imóvel Residencial',
      tipo: 'Apartamento',
      local: 'Campeche',
      valor: '2.300,00',
      dormitorios: 1,
      suites: 1,
      banheiros: 2,
      salas: 1,
      garagem: 4,
      garagem_coberta: 2,
      area_total: 180,
      area_util: 180,
      estrutura: ['Ar condicionado', 'Churrasqueira', 'Despensa', 'Escritório'],
      mapa: 'https://goo.gl/maps/BkjiniR8JcaRHeiw5',
    },
    {
      id: '5',
      titulo: 'Casa com 3 dormitorios no Campeche com ótima vista',
      imagem:
        'https://images.pexels.com/photos/2468773/pexels-photo-2468773.jpeg?cs=srgb&dl=pexels-krisp-cut-2468773.jpg&fm=jpg',
      detalhe: 'Imóvel Residencial',
      tipo: 'Apartamento',
      local: 'Coqueiros',
      valor: '1.800,00',
      dormitorios: 1,
      suites: 1,
      banheiros: 2,
      salas: 1,
      garagem: 4,
      garagem_coberta: 2,
      area_total: 180,
      area_util: 180,
      estrutura: ['Ar condicionado', 'Churrasqueira', 'Despensa', 'Escritório'],
      mapa: 'https://goo.gl/maps/BkjiniR8JcaRHeiw5',
    },
    {
      id: '6',
      titulo: 'Apartamento no prédio XPTO com vista para a Lagoa',
      imagem:
        'https://images.pexels.com/photos/1296203/pexels-photo-1296203.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      detalhe: 'Comercial/Industrial',
      tipo: 'Sala Comercial',
      local: 'Itacorubi',
      valor: '4.000,00',
      dormitorios: 1,
      suites: 1,
      banheiros: 2,
      salas: 1,
      garagem: 4,
      garagem_coberta: 2,
      area_total: 180,
      area_util: 180,
      estrutura: ['Ar condicionado', 'Churrasqueira', 'Despensa', 'Escritório'],
      mapa: 'https://goo.gl/maps/BkjiniR8JcaRHeiw5',
    },
  ],
}
