import Head from 'next/head'
import Imoveis from '../components/Imoveis'
import Banner from '../components/Banner'
import Filter from '../components/Filter'
import Encontre from '../components/Encontre'
import { imoveis } from '../lib/data'

export default function Home({ imoveisAluguel, imoveisVenda }) {
  return (
    <>
      <Head>
        <title>Teste VistaSoft</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Banner />
      <Filter />
      <Encontre />
      <Imoveis imoveisAluguel={imoveisAluguel} imoveisVenda={imoveisVenda} />
    </>
  )
}

export const getStaticProps = async () => {
  const [imoveisAluguel, imoveisVenda] = [imoveis.aluguel, imoveis.venda]

  return {
    props: {
      imoveisAluguel,
      imoveisVenda,
    },
  }
}
