import Head from 'next/head'
import Image from 'next/image'
import imoveis from '../db.json'
import Imoveis from '../components/Imoveis'
import Banner from '../components/Banner'
import Filter from '../components/Filter'
import Encontre from '../components/Encontre'

const imoveisAluguel = imoveis.aluguel
const imoveisVenda = imoveis.venda

export default function Home() {
  return (
    <>
      <Head>
        <title>Teste VistaSoft</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Banner />
      <Filter />
      <Encontre />
      <Imoveis imoveisAluguel={imoveisAluguel} imoveisVenda={imoveisVenda} />
    </>
  )
}
